// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aspDotNet.DataAccsessLayer.Concrate;

#nullable disable

namespace aspDotNet.DataAccsessLayer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240616105633_mig_edit_identity")]
    partial class mig_edit_identity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("aspDotNet.EntityLayer.Concrate.CustommerAccount", b =>
                {
                    b.Property<int>("CustommerAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustommerAccountId"));

                    b.Property<string>("BankBranch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CustommerAccountBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CustommerAccountCurrency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustommerAccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustommerAccountId");

                    b.ToTable("CustommerAccounts");
                });

            modelBuilder.Entity("aspDotNet.EntityLayer.Concrate.CustommerAccountProcess", b =>
                {
                    b.Property<int>("CustommerAccountProcessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustommerAccountProcessId"));

                    b.Property<decimal>("CustommerAccountProcessAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CustommerAccountProcessDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustommerAccountProcessType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustommerAccountProcessId");

                    b.ToTable("CustommerAccountsProcess");
                });
#pragma warning restore 612, 618
        }
    }
}
